import { Config } from "effect";

/**
 * Optional native engine executable path supplied by embedding apps or tests.
 */
export const EnginePathConfig = Config.option(Config.string("GG_ENGINE_PATH"));

/**
 * Effect configuration recipe for launching a managed native engine process.
 *
 * @remarks
 * These are user/configurable process-launch inputs. Runtime-enforced child
 * process variables such as `GG_ENGINE_TRANSPORT` and `GG_ENGINE_HTTP_AUTH_TOKEN`
 * are intentionally generated by the launcher instead of being read from config.
 */
export const EngineProcessConfig = Config.all({
  enginePath: EnginePathConfig,
  readinessTimeoutMs: Config.number("ENGINE_READINESS_TIMEOUT_MS").pipe(Config.withDefault(10_000)),
});

/**
 * Runtime TypeScript type loaded by {@link EngineProcessConfig}.
 */
export type EngineProcessConfig = Config.Success<typeof EngineProcessConfig>;
