import * as m from "../paraglide/messages.js";
import { baseLocale, locales, type Locale } from "../paraglide/runtime.js";

export { baseLocale as defaultStudioLocale, locales as studioLocales };
export type StudioLocale = Locale;

export function normalizeStudioLocale(locale: string | null | undefined): StudioLocale {
  const normalized = locale?.trim().toLowerCase();
  if (normalized === "de" || normalized === "de-de") {
    return "de-DE";
  }
  if (normalized === "en" || normalized === "en-us") {
    return "en-US";
  }
  return baseLocale;
}

function localeOptions(locale: string | null | undefined): { locale: StudioLocale } {
  return { locale: normalizeStudioLocale(locale) };
}

export function getStudioMessages(locale: string | null | undefined) {
  const options = localeOptions(locale);
  return {
    app: {
      title: m.studio_app_title(undefined, options),
      subtitle: m.studio_app_subtitle(undefined, options),
      shellState: m.studio_app_shellState(undefined, options),
    },
    notices: {
      refreshFailed: m.studio_notices_refreshFailed(undefined, options),
      actionFailed: m.studio_notices_actionFailed(undefined, options),
      rpcTimedOut: m.studio_notices_rpcTimedOut(undefined, options),
      directoryPickerTimedOut: m.studio_notices_directoryPickerTimedOut(undefined, options),
      permissionsRefreshed: m.studio_notices_permissionsRefreshed(undefined, options),
      captureStarted: m.studio_notices_captureStarted(undefined, options),
      previewStateMismatch: m.studio_notices_previewStateMismatch(undefined, options),
      captureStopped: m.studio_notices_captureStopped(undefined, options),
      recordingStarted: m.studio_notices_recordingStarted(undefined, options),
      recordingFinished: m.studio_notices_recordingFinished(undefined, options),
      recordingStartNotReady: m.studio_notices_recordingStartNotReady(undefined, options),
      exportMissingRecording: m.studio_notices_exportMissingRecording(undefined, options),
      exportMissingPreset: m.studio_notices_exportMissingPreset(undefined, options),
      exportComplete: (outputURL: string) =>
        m.studio_notices_exportComplete({ outputURL }, options),
      projectOpened: m.studio_notices_projectOpened(undefined, options),
      projectSaveTarget: (path: string) => m.studio_notices_projectSaveTarget({ path }, options),
      projectSaved: (path: string) => m.studio_notices_projectSaved({ path }, options),
      selectWindowFirst: m.studio_notices_selectWindowFirst(undefined, options),
      screenPermissionRequired: m.studio_notices_screenPermissionRequired(undefined, options),
      inputTrackingDegraded: m.studio_notices_inputTrackingDegraded(undefined, options),
    },
    sections: {
      leftRail: m.studio_sections_leftRail(undefined, options),
      center: m.studio_sections_center(undefined, options),
      timeline: m.studio_sections_timeline(undefined, options),
      inspector: m.studio_sections_inspector(undefined, options),
    },
    modes: {
      capture: m.studio_modes_capture(undefined, options),
      edit: m.studio_modes_edit(undefined, options),
      deliver: m.studio_modes_deliver(undefined, options),
    },
    workspace: {
      editStageTitle: m.studio_workspace_editStageTitle(undefined, options),
      deliverSummaryTitle: m.studio_workspace_deliverSummaryTitle(undefined, options),
      deliverSummarySubtitle: m.studio_workspace_deliverSummarySubtitle(undefined, options),
      exportTitle: m.studio_workspace_exportTitle(undefined, options),
      exportSubtitle: m.studio_workspace_exportSubtitle(undefined, options),
    },
    actions: {
      refresh: m.studio_actions_refresh(undefined, options),
      requestScreen: m.studio_actions_requestScreen(undefined, options),
      requestMic: m.studio_actions_requestMic(undefined, options),
      requestInput: m.studio_actions_requestInput(undefined, options),
      openSettings: m.studio_actions_openSettings(undefined, options),
      startPreview: m.studio_actions_startPreview(undefined, options),
      stopPreview: m.studio_actions_stopPreview(undefined, options),
      startRecording: m.studio_actions_startRecording(undefined, options),
      stopRecording: m.studio_actions_stopRecording(undefined, options),
      recordDisplay: m.studio_actions_recordDisplay(undefined, options),
      recordCurrentWindow: m.studio_actions_recordCurrentWindow(undefined, options),
      recordChooseWindow: m.studio_actions_recordChooseWindow(undefined, options),
      exportNow: m.studio_actions_exportNow(undefined, options),
      openProject: m.studio_actions_openProject(undefined, options),
      saveProject: m.studio_actions_saveProject(undefined, options),
      saveProjectAs: m.studio_actions_saveProjectAs(undefined, options),
      openRecent: m.studio_actions_openRecent(undefined, options),
      playPause: m.studio_actions_playPause(undefined, options),
      setTrimIn: m.studio_actions_setTrimIn(undefined, options),
      setTrimOut: m.studio_actions_setTrimOut(undefined, options),
      timelineToolSelect: m.studio_actions_timelineToolSelect(undefined, options),
      timelineToolTrim: m.studio_actions_timelineToolTrim(undefined, options),
      timelineToolBlade: m.studio_actions_timelineToolBlade(undefined, options),
      timelineZoomIn: m.studio_actions_timelineZoomIn(undefined, options),
      timelineZoomOut: m.studio_actions_timelineZoomOut(undefined, options),
      timelineZoomReset: m.studio_actions_timelineZoomReset(undefined, options),
      toggleLeftPane: m.studio_actions_toggleLeftPane(undefined, options),
      toggleRightPane: m.studio_actions_toggleRightPane(undefined, options),
      toggleTimeline: m.studio_actions_toggleTimeline(undefined, options),
      resetLayout: m.studio_actions_resetLayout(undefined, options),
      recordShortcut: m.studio_actions_recordShortcut(undefined, options),
      cancelShortcutRecording: m.studio_actions_cancelShortcutRecording(undefined, options),
      resetShortcut: m.studio_actions_resetShortcut(undefined, options),
    },
    shortcuts: {
      title: m.studio_shortcuts_title(undefined, options),
      playPause: m.studio_shortcuts_playPause(undefined, options),
      record: m.studio_shortcuts_record(undefined, options),
      blade: m.studio_shortcuts_blade(undefined, options),
      trimIn: m.studio_shortcuts_trimIn(undefined, options),
      trimOut: m.studio_shortcuts_trimOut(undefined, options),
      save: m.studio_shortcuts_save(undefined, options),
      saveAs: m.studio_shortcuts_saveAs(undefined, options),
      export: m.studio_shortcuts_export(undefined, options),
    },
    labels: {
      language: m.studio_labels_language(undefined, options),
      density: m.studio_labels_density(undefined, options),
      densityComfortable: m.studio_labels_densityComfortable(undefined, options),
      densityCompact: m.studio_labels_densityCompact(undefined, options),
      localeEnglish: m.studio_labels_localeEnglish(undefined, options),
      localeGerman: m.studio_labels_localeGerman(undefined, options),
      permissionReady: m.studio_labels_permissionReady(undefined, options),
      permissionRequired: m.studio_labels_permissionRequired(undefined, options),
      screen: m.studio_labels_screen(undefined, options),
      microphone: m.studio_labels_microphone(undefined, options),
      captureSource: m.studio_labels_captureSource(undefined, options),
      display: m.studio_labels_display(undefined, options),
      window: m.studio_labels_window(undefined, options),
      noDisplays: m.studio_labels_noDisplays(undefined, options),
      noWindows: m.studio_labels_noWindows(undefined, options),
      includeMic: m.studio_labels_includeMic(undefined, options),
      trackInput: m.studio_labels_trackInput(undefined, options),
      captureFrameRate: m.studio_labels_captureFrameRate(undefined, options),
      singleKeyShortcuts: m.studio_labels_singleKeyShortcuts(undefined, options),
      shortcutDefault: m.studio_labels_shortcutDefault(undefined, options),
      shortcutCustom: m.studio_labels_shortcutCustom(undefined, options),
      shortcutRecording: m.studio_labels_shortcutRecording(undefined, options),
      inputMonitoring: m.studio_labels_inputMonitoring(undefined, options),
      technicalFeedback: m.studio_labels_technicalFeedback(undefined, options),
      status: m.studio_labels_status(undefined, options),
      duration: m.studio_labels_duration(undefined, options),
      sourceDroppedFrames: m.studio_labels_sourceDroppedFrames(undefined, options),
      writerDroppedFrames: m.studio_labels_writerDroppedFrames(undefined, options),
      writerBackpressureDrops: m.studio_labels_writerBackpressureDrops(undefined, options),
      achievedFps: m.studio_labels_achievedFps(undefined, options),
      captureCallback: m.studio_labels_captureCallback(undefined, options),
      recordQueueLag: m.studio_labels_recordQueueLag(undefined, options),
      writerAppend: m.studio_labels_writerAppend(undefined, options),
      cpuUsage: m.studio_labels_cpuUsage(undefined, options),
      memoryUsage: m.studio_labels_memoryUsage(undefined, options),
      recordingBitrate: m.studio_labels_recordingBitrate(undefined, options),
      recordingURL: m.studio_labels_recordingURL(undefined, options),
      projectPath: m.studio_labels_projectPath(undefined, options),
      eventsURL: m.studio_labels_eventsURL(undefined, options),
      notSaved: m.studio_labels_notSaved(undefined, options),
      idle: m.studio_labels_idle(undefined, options),
      previewing: m.studio_labels_previewing(undefined, options),
      recording: m.studio_labels_recording(undefined, options),
      trimInSeconds: m.studio_labels_trimInSeconds(undefined, options),
      trimOutSeconds: m.studio_labels_trimOutSeconds(undefined, options),
      playhead: m.studio_labels_playhead(undefined, options),
      timelineTools: m.studio_labels_timelineTools(undefined, options),
      timelineSnap: m.studio_labels_timelineSnap(undefined, options),
      timelineRipple: m.studio_labels_timelineRipple(undefined, options),
      timelineZoom: m.studio_labels_timelineZoom(undefined, options),
      timelineLaneLock: m.studio_labels_timelineLaneLock(undefined, options),
      timelineLaneMute: m.studio_labels_timelineLaneMute(undefined, options),
      timelineLaneSolo: m.studio_labels_timelineLaneSolo(undefined, options),
      playbackRate: m.studio_labels_playbackRate(undefined, options),
      preset: m.studio_labels_preset(undefined, options),
      fileName: m.studio_labels_fileName(undefined, options),
      activeProject: m.studio_labels_activeProject(undefined, options),
      projectUtilitySubtitle: m.studio_labels_projectUtilitySubtitle(undefined, options),
      projectName: m.studio_labels_projectName(undefined, options),
      captureSourceMetadata: m.studio_labels_captureSourceMetadata(undefined, options),
      captureResolution: m.studio_labels_captureResolution(undefined, options),
      captureScale: m.studio_labels_captureScale(undefined, options),
      recentProjects: m.studio_labels_recentProjects(undefined, options),
      lastOpened: m.studio_labels_lastOpened(undefined, options),
      loadingRecentProjects: m.studio_labels_loadingRecentProjects(undefined, options),
      noRecentProjects: m.studio_labels_noRecentProjects(undefined, options),
      mediaBin: m.studio_labels_mediaBin(undefined, options),
      mediaReady: m.studio_labels_mediaReady(undefined, options),
      mediaMissing: m.studio_labels_mediaMissing(undefined, options),
      sourceMonitor: m.studio_labels_sourceMonitor(undefined, options),
      audioMixer: m.studio_labels_audioMixer(undefined, options),
      masterChannel: m.studio_labels_masterChannel(undefined, options),
      mute: m.studio_labels_mute(undefined, options),
      unmute: m.studio_labels_unmute(undefined, options),
      autoZoomSection: m.studio_labels_autoZoomSection(undefined, options),
      autoZoomEnabled: m.studio_labels_autoZoomEnabled(undefined, options),
      autoZoomIntensity: (value: number) => m.studio_labels_autoZoomIntensity({ value }, options),
      minimumKeyframeInterval: m.studio_labels_minimumKeyframeInterval(undefined, options),
      backgroundFraming: m.studio_labels_backgroundFraming(undefined, options),
      backgroundColor: m.studio_labels_backgroundColor(undefined, options),
      backgroundPadding: m.studio_labels_backgroundPadding(undefined, options),
      cornerRoundness: m.studio_labels_cornerRoundness(undefined, options),
      shadowStrength: m.studio_labels_shadowStrength(undefined, options),
      motionBlur: m.studio_labels_motionBlur(undefined, options),
      simulatorAutoCrop: m.studio_labels_simulatorAutoCrop(undefined, options),
      segmentOverrides: m.studio_labels_segmentOverrides(undefined, options),
      phaseTwoLabel: m.studio_labels_phaseTwoLabel(undefined, options),
      phaseThreeLabel: m.studio_labels_phaseThreeLabel(undefined, options),
      sourceWindowList: m.studio_labels_sourceWindowList(undefined, options),
      sourceWindowApp: m.studio_labels_sourceWindowApp(undefined, options),
      sourceWindowTitle: m.studio_labels_sourceWindowTitle(undefined, options),
      sourceWindowSize: m.studio_labels_sourceWindowSize(undefined, options),
      timelineLaneVideo: m.studio_labels_timelineLaneVideo(undefined, options),
      timelineLaneAudio: m.studio_labels_timelineLaneAudio(undefined, options),
      timelineLaneEvents: m.studio_labels_timelineLaneEvents(undefined, options),
      timelineMarkerMove: m.studio_labels_timelineMarkerMove(undefined, options),
      timelineMarkerClick: m.studio_labels_timelineMarkerClick(undefined, options),
      timelineMarkerMixed: m.studio_labels_timelineMarkerMixed(undefined, options),
      timelineClipAria: (laneLabel: string, startSeconds: number, endSeconds: number) =>
        m.studio_labels_timelineClipAria(
          { laneLabel, startSeconds: startSeconds.toFixed(2), endSeconds: endSeconds.toFixed(2) },
          options,
        ),
      timelineGapAria: (laneLabel: string, startSeconds: number, endSeconds: number) =>
        m.studio_labels_timelineGapAria(
          { laneLabel, startSeconds: startSeconds.toFixed(2), endSeconds: endSeconds.toFixed(2) },
          options,
        ),
      timelineMarkerAria: (markerKindLabel: string, timestampSeconds: number) =>
        m.studio_labels_timelineMarkerAria(
          { markerKindLabel, timestampSeconds: timestampSeconds.toFixed(2) },
          options,
        ),
      resizeTimeline: m.studio_labels_resizeTimeline(undefined, options),
      resizeLeftPane: m.studio_labels_resizeLeftPane(undefined, options),
      resizeRightPane: m.studio_labels_resizeRightPane(undefined, options),
    },
    values: {
      granted: m.studio_values_granted(undefined, options),
      notGranted: m.studio_values_notGranted(undefined, options),
      unknown: m.studio_values_unknown(undefined, options),
      primary: m.studio_values_primary(undefined, options),
      untitled: m.studio_values_untitled(undefined, options),
      on: m.studio_values_on(undefined, options),
      off: m.studio_values_off(undefined, options),
    },
    inspectorTabs: {
      capture: m.studio_inspectorTabs_capture(undefined, options),
      effects: m.studio_inspectorTabs_effects(undefined, options),
      export: m.studio_inspectorTabs_export(undefined, options),
      project: m.studio_inspectorTabs_project(undefined, options),
      advanced: m.studio_inspectorTabs_advanced(undefined, options),
    },
    inspector: {
      views: {
        timelineClipVideo: {
          title: m.studio_inspector_views_timelineClipVideo_title(undefined, options),
          subtitle: m.studio_inspector_views_timelineClipVideo_subtitle(undefined, options),
        },
        timelineClipAudio: {
          title: m.studio_inspector_views_timelineClipAudio_title(undefined, options),
          subtitle: m.studio_inspector_views_timelineClipAudio_subtitle(undefined, options),
        },
        timelineMarker: {
          title: m.studio_inspector_views_timelineMarker_title(undefined, options),
          subtitle: m.studio_inspector_views_timelineMarker_subtitle(undefined, options),
        },
        captureWindow: {
          title: m.studio_inspector_views_captureWindow_title(undefined, options),
          subtitle: m.studio_inspector_views_captureWindow_subtitle(undefined, options),
        },
        exportPreset: {
          title: m.studio_inspector_views_exportPreset_title(undefined, options),
          subtitle: m.studio_inspector_views_exportPreset_subtitle(undefined, options),
        },
        captureDefault: {
          title: m.studio_inspector_views_captureDefault_title(undefined, options),
          subtitle: m.studio_inspector_views_captureDefault_subtitle(undefined, options),
        },
        editDefault: {
          title: m.studio_inspector_views_editDefault_title(undefined, options),
          subtitle: m.studio_inspector_views_editDefault_subtitle(undefined, options),
        },
        deliverDefault: {
          title: m.studio_inspector_views_deliverDefault_title(undefined, options),
          subtitle: m.studio_inspector_views_deliverDefault_subtitle(undefined, options),
        },
      },
      cards: {
        selectedClip: m.studio_inspector_cards_selectedClip(undefined, options),
        selectedEventMarker: m.studio_inspector_cards_selectedEventMarker(undefined, options),
        selectedWindow: m.studio_inspector_cards_selectedWindow(undefined, options),
        selectedPreset: m.studio_inspector_cards_selectedPreset(undefined, options),
        activePreset: m.studio_inspector_cards_activePreset(undefined, options),
        trimWindow: m.studio_inspector_cards_trimWindow(undefined, options),
      },
      fields: {
        lane: m.studio_inspector_fields_lane(undefined, options),
        start: m.studio_inspector_fields_start(undefined, options),
        end: m.studio_inspector_fields_end(undefined, options),
        duration: m.studio_inspector_fields_duration(undefined, options),
        type: m.studio_inspector_fields_type(undefined, options),
        time: m.studio_inspector_fields_time(undefined, options),
        density: m.studio_inspector_fields_density(undefined, options),
        app: m.studio_inspector_fields_app(undefined, options),
        title: m.studio_inspector_fields_title(undefined, options),
        windowId: m.studio_inspector_fields_windowId(undefined, options),
        fileType: m.studio_inspector_fields_fileType(undefined, options),
      },
      actions: {
        setTrimInToClipStart: m.studio_inspector_actions_setTrimInToClipStart(undefined, options),
        setTrimOutToClipEnd: m.studio_inspector_actions_setTrimOutToClipEnd(undefined, options),
        splitClipAtPlayhead: m.studio_inspector_actions_splitClipAtPlayhead(undefined, options),
        liftClip: m.studio_inspector_actions_liftClip(undefined, options),
        moveClipEarlier: m.studio_inspector_actions_moveClipEarlier(undefined, options),
        moveClipLater: m.studio_inspector_actions_moveClipLater(undefined, options),
        deleteClip: (rippleEnabled: boolean) =>
          rippleEnabled
            ? m.studio_inspector_actions_deleteClipRipple(undefined, options)
            : m.studio_inspector_actions_deleteClip(undefined, options),
        jumpPlayheadToMarker: m.studio_inspector_actions_jumpPlayheadToMarker(undefined, options),
      },
    },
    helper: {
      degradedModeTitle: m.studio_helper_degradedModeTitle(undefined, options),
      degradedModeBody: m.studio_helper_degradedModeBody(undefined, options),
      emptyPreviewTitle: m.studio_helper_emptyPreviewTitle(undefined, options),
      emptyPreviewBody: m.studio_helper_emptyPreviewBody(undefined, options),
      activePreviewTitle: m.studio_helper_activePreviewTitle(undefined, options),
      activePreviewBody: m.studio_helper_activePreviewBody(undefined, options),
      phaseScaffoldTitle: m.studio_helper_phaseScaffoldTitle(undefined, options),
      phaseScaffoldBody: m.studio_helper_phaseScaffoldBody(undefined, options),
      singleKeyShortcuts: m.studio_helper_singleKeyShortcuts(undefined, options),
      shortcutCustomization: m.studio_helper_shortcutCustomization(undefined, options),
      shortcutRecording: m.studio_helper_shortcutRecording(undefined, options),
      shortcutInvalid: (reason: string) => m.studio_helper_shortcutInvalid({ reason }, options),
      shortcutConflict: (label: string) => m.studio_helper_shortcutConflict({ label }, options),
      shortcutDefault: (binding: string) => m.studio_helper_shortcutDefault({ binding }, options),
      shortcutCustomized: (binding: string) =>
        m.studio_helper_shortcutCustomized({ binding }, options),
      recordToEnableAction: m.studio_helper_recordToEnableAction(undefined, options),
    },
  };
}

export type StudioMessages = ReturnType<typeof getStudioMessages>;

export function getDesktopMenuMessages(locale: string | null | undefined) {
  const options = localeOptions(locale);
  return {
    file: m.desktopMenu_file(undefined, options),
    openProject: m.desktopMenu_openProject(undefined, options),
    saveProject: m.desktopMenu_saveProject(undefined, options),
    saveProjectAs: m.desktopMenu_saveProjectAs(undefined, options),
    export: m.desktopMenu_export(undefined, options),
    edit: m.desktopMenu_edit(undefined, options),
    capture: m.desktopMenu_capture(undefined, options),
    startRecording: m.desktopMenu_startRecording(undefined, options),
    stopRecording: m.desktopMenu_stopRecording(undefined, options),
    startPreview: m.desktopMenu_startPreview(undefined, options),
    stopPreview: m.desktopMenu_stopPreview(undefined, options),
    refreshSources: m.desktopMenu_refreshSources(undefined, options),
    timeline: m.desktopMenu_timeline(undefined, options),
    playPause: m.desktopMenu_playPause(undefined, options),
    setTrimIn: m.desktopMenu_setTrimIn(undefined, options),
    setTrimOut: m.desktopMenu_setTrimOut(undefined, options),
    toggleTimeline: m.desktopMenu_toggleTimeline(undefined, options),
    view: m.desktopMenu_view(undefined, options),
    language: m.desktopMenu_language(undefined, options),
    languageEnglish: m.desktopMenu_languageEnglish(undefined, options),
    languageGerman: m.desktopMenu_languageGerman(undefined, options),
    density: m.desktopMenu_density(undefined, options),
    densityComfortable: m.desktopMenu_densityComfortable(undefined, options),
    densityCompact: m.desktopMenu_densityCompact(undefined, options),
    toggleDeveloperTools: m.desktopMenu_toggleDeveloperTools(undefined, options),
    window: m.desktopMenu_window(undefined, options),
    help: m.desktopMenu_help(undefined, options),
    documentation: m.desktopMenu_documentation(undefined, options),
    quit: m.desktopMenu_quit(undefined, options),
  };
}

export type DesktopMenuMessages = ReturnType<typeof getDesktopMenuMessages>;
export const enUS = getStudioMessages("en-US");
export const deDE = getStudioMessages("de-DE");
