[package]
name = "native-foundation"
version = "1.0.0"
edition = "2021"

[lib]
name = "native_foundation"
path = "src/lib.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
protocol-rust = { path = "../protocol-rust" }
time = { version = "0.3", features = ["formatting"] }
libc = "0.2"
