// Generated by Scripts/generate_engine_bindings.mjs. Do not edit manually.
// swiftlint:disable cyclomatic_complexity

import Foundation

/// Canonical engine RPC method names generated from packages/engine/src/protocol/rpc/group.ts.
public enum EngineMethod: Codable, CaseIterable, Equatable {
    case systemPing
    case engineCapabilities
    case agentPreflight
    case agentRun
    case agentStatus
    case agentApply
    case permissionsGet
    case permissionsRequestScreenRecording
    case permissionsRequestMicrophone
    case permissionsRequestInputMonitoring
    case permissionsOpenInputMonitoringSettings
    case sourcesList
    case captureStartDisplay
    case captureStartCurrentWindow
    case captureStartWindow
    case captureStop
    case recordingStart
    case recordingStop
    case captureStatus
    case captureStatusStream
    case capturePreviewFrame
    case capturePreviewFrameStream
    case exportInfo
    case exportRun
    case exportRunCutPlan
    case projectCurrent
    case projectOpen
    case projectSave
    case projectRecents

    public init?(method: String) {
        switch method {
        case "system.ping": self = .systemPing
        case "engine.capabilities": self = .engineCapabilities
        case "agent.preflight": self = .agentPreflight
        case "agent.run": self = .agentRun
        case "agent.status": self = .agentStatus
        case "agent.apply": self = .agentApply
        case "permissions.get": self = .permissionsGet
        case "permissions.requestScreenRecording": self = .permissionsRequestScreenRecording
        case "permissions.requestMicrophone": self = .permissionsRequestMicrophone
        case "permissions.requestInputMonitoring": self = .permissionsRequestInputMonitoring
        case "permissions.openInputMonitoringSettings": self = .permissionsOpenInputMonitoringSettings
        case "sources.list": self = .sourcesList
        case "capture.startDisplay": self = .captureStartDisplay
        case "capture.startCurrentWindow": self = .captureStartCurrentWindow
        case "capture.startWindow": self = .captureStartWindow
        case "capture.stop": self = .captureStop
        case "recording.start": self = .recordingStart
        case "recording.stop": self = .recordingStop
        case "capture.status": self = .captureStatus
        case "capture.statusStream": self = .captureStatusStream
        case "capture.previewFrame": self = .capturePreviewFrame
        case "capture.previewFrameStream": self = .capturePreviewFrameStream
        case "export.info": self = .exportInfo
        case "export.run": self = .exportRun
        case "export.runCutPlan": self = .exportRunCutPlan
        case "project.current": self = .projectCurrent
        case "project.open": self = .projectOpen
        case "project.save": self = .projectSave
        case "project.recents": self = .projectRecents
        default: return nil
        }
    }

    public var method: String {
        switch self {
        case .systemPing: "system.ping"
        case .engineCapabilities: "engine.capabilities"
        case .agentPreflight: "agent.preflight"
        case .agentRun: "agent.run"
        case .agentStatus: "agent.status"
        case .agentApply: "agent.apply"
        case .permissionsGet: "permissions.get"
        case .permissionsRequestScreenRecording: "permissions.requestScreenRecording"
        case .permissionsRequestMicrophone: "permissions.requestMicrophone"
        case .permissionsRequestInputMonitoring: "permissions.requestInputMonitoring"
        case .permissionsOpenInputMonitoringSettings: "permissions.openInputMonitoringSettings"
        case .sourcesList: "sources.list"
        case .captureStartDisplay: "capture.startDisplay"
        case .captureStartCurrentWindow: "capture.startCurrentWindow"
        case .captureStartWindow: "capture.startWindow"
        case .captureStop: "capture.stop"
        case .recordingStart: "recording.start"
        case .recordingStop: "recording.stop"
        case .captureStatus: "capture.status"
        case .captureStatusStream: "capture.statusStream"
        case .capturePreviewFrame: "capture.previewFrame"
        case .capturePreviewFrameStream: "capture.previewFrameStream"
        case .exportInfo: "export.info"
        case .exportRun: "export.run"
        case .exportRunCutPlan: "export.runCutPlan"
        case .projectCurrent: "project.current"
        case .projectOpen: "project.open"
        case .projectSave: "project.save"
        case .projectRecents: "project.recents"
        }
    }
}
