#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const rpcsPath = path.join(repoRoot, "packages/engine/src/protocol/rpc/group.ts");
const swiftOutputPath = path.join(
  repoRoot,
  "engines/protocol-swift/EngineMethods.generated.swift",
);

function firstQuotedString(source) {
  const match = source.match(/"([^"]+)"/);
  return match?.[1] ?? null;
}

function parseRpcs(source) {
  const entries = [];
  let pendingVariant = null;

  for (const line of source.split(/\r?\n/)) {
    const trimmed = line.trim();
    const classMatch = trimmed.match(/^export class\s+([A-Za-z0-9_]+)\s+extends\s+(?:rpc|streamRpc)\(/);
    if (classMatch) {
      pendingVariant = classMatch[1];
      const method = firstQuotedString(trimmed.slice(classMatch[0].length));
      if (method) {
        entries.push([pendingVariant, method]);
        pendingVariant = null;
      }
      continue;
    }

    if (pendingVariant) {
      const method = firstQuotedString(trimmed);
      if (method) {
        entries.push([pendingVariant, method]);
        pendingVariant = null;
      }
    }
  }

  if (entries.length === 0) {
    throw new Error(`No engine RPC methods discovered in ${rpcsPath}`);
  }

  return entries;
}

function swiftCaseName(variant) {
  return variant[0].toLowerCase() + variant.slice(1);
}

function renderSwift(entries) {
  const cases = entries
    .map(([variant]) => `    case ${swiftCaseName(variant)}`)
    .join("\n");
  const initializerCases = entries
    .map(([variant, method]) => `        case "${method}": self = .${swiftCaseName(variant)}`)
    .join("\n");
  const methodCases = entries
    .map(([variant, method]) => `        case .${swiftCaseName(variant)}: return "${method}"`)
    .join("\n");

  return `// Generated by Scripts/generate_engine_bindings.mjs. Do not edit manually.\n\nimport Foundation\n\n/// Canonical engine RPC method names generated from packages/engine/src/protocol/rpc/group.ts.\npublic enum EngineMethod: Codable, CaseIterable, Equatable {\n${cases}\n\n    public init?(method: String) {\n        switch method {\n${initializerCases}\n        default: return nil\n        }\n    }\n\n    public var method: String {\n        switch self {\n${methodCases}\n        }\n    }\n}\n`;
}

const entries = parseRpcs(readFileSync(rpcsPath, "utf8"));
writeFileSync(swiftOutputPath, renderSwift(entries));
console.log(`Generated ${path.relative(repoRoot, swiftOutputPath)} (${entries.length} methods)`);
