#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if ! command -v java >/dev/null 2>&1 || ! java -version >/dev/null 2>&1; then
  echo "Java is required for OpenAPI generation. Install a JDK and ensure 'java' is on PATH (macOS/Homebrew: brew install openjdk; export PATH=\"/opt/homebrew/opt/openjdk/bin:\$PATH\")." >&2
  exit 1
fi

OPENAPI_FILE="$ROOT_DIR/packages/engine-contract/generated/engine.openapi.json"
RUST_CONFIG_FILE="$ROOT_DIR/engines/protocol-rust/openapi-generator-config.json"
RUST_TEMPLATE_DIR="$ROOT_DIR/engines/protocol-rust/openapi-generator-templates"
SWIFT_OPENAPI_FILE="$ROOT_DIR/engines/protocol-swift/Sources/EngineProtocol/openapi.json"

(
  cd "$ROOT_DIR/packages/engine-contract"
  bun run generate:openapi
  bun run check:contract
)

mkdir -p "$(dirname "$SWIFT_OPENAPI_FILE")"
cp "$OPENAPI_FILE" "$SWIFT_OPENAPI_FILE"

npx --yes @openapitools/openapi-generator-cli generate \
  -g rust-axum \
  -i "$OPENAPI_FILE" \
  -o "$ROOT_DIR/engines/protocol-rust" \
  -c "$RUST_CONFIG_FILE" \
  -t "$RUST_TEMPLATE_DIR"

# OpenAPI Generator rewrites package metadata. Keep project-owned metadata stable.
python3 - <<'PY'
from pathlib import Path
path = Path('engines/protocol-rust/Cargo.toml')
text = path.read_text()
text = text.replace('version = "0.0.1"', 'version = "1.0.0"')
text = text.replace('authors = ["OpenAPI Generator team and contributors"]', 'authors = ["GuerillaGlass contributors"]')
text = text.replace(
    'description = "No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)"',
    'description = "Generated Rust server bindings for the GuerillaGlass Engine Contract v2 HTTP/OpenAPI API"',
)
if 'tower = { version = "0.5", features = ["util"] }' not in text:
    text = text.replace('[dev-dependencies]\n', '[dev-dependencies]\ntower = { version = "0.5", features = ["util"] }\n')
path.write_text(text)
Path('engines/protocol-rust/README.md').write_text('''# protocol-rust\n\nGenerated Rust server bindings for the GuerillaGlass Engine Contract v2 HTTP/OpenAPI API.\n\n## Source of truth\n\n- TypeScript/Effect contract: `packages/engine-contract/src/httpApi.ts`\n- Generated OpenAPI: `packages/engine-contract/generated/engine.openapi.json`\n- Rust generator config: `engines/protocol-rust/openapi-generator-config.json`\n\nThis package is intentionally v2-only. It only exposes generated HTTP/OpenAPI bindings and server helpers.\n\n## Regenerate\n\n```bash\nbun run protocol:generate-bindings\n```\n\n## Check\n\n```bash\ncargo check --manifest-path engines/protocol-rust/Cargo.toml\n```\n''')
PY
