import type { StudioMessages } from "./en";

export const deDE: StudioMessages = {
  app: {
    title: "Guerillaglass",
    subtitle: "Desktop-Editor-Shell",
    shellState: "Spezifikationskonformer Aufnahme- und Editier-Workflow",
  },
  notices: {
    refreshFailed: "Aktualisierung des App-Status fehlgeschlagen.",
    actionFailed: "Aktion fehlgeschlagen.",
    rpcTimedOut:
      "RPC-Anfrage hat das Zeitlimit erreicht. Erneut versuchen oder offene Dateidialoge zuerst schließen.",
    directoryPickerTimedOut:
      "Der Verzeichnisdialog hat vor Abschluss das Zeitlimit erreicht. Aktion erneut starten, wenn du bereit bist.",
    permissionsRefreshed: "Berechtigungen aktualisiert.",
    captureStarted: "Aufnahmevorschau gestartet.",
    previewStateMismatch:
      "Vorschau-Befehl gesendet, aber der Engine-Status bestätigt noch keine Live-Vorschau. Quellen-Berechtigungen prüfen und erneut versuchen.",
    captureStopped: "Aufnahme gestoppt.",
    recordingStarted: "Aufzeichnung gestartet.",
    recordingFinished: "Aufzeichnung beendet.",
    exportMissingRecording: "Keine Aufzeichnung für den Export verfügbar.",
    exportMissingPreset: "Kein Export-Preset ausgewählt.",
    exportComplete: (outputURL: string) => `Export abgeschlossen: ${outputURL}`,
    projectOpened: "Projekt geöffnet.",
    projectSaved: (path: string) => `Projekt gespeichert unter ${path}`,
    selectWindowFirst: "Wähle vor dem Start der Aufnahme ein Fenster aus.",
    screenPermissionRequired:
      "Bildschirmaufnahme-Berechtigung ist erforderlich. Aktiviere Guerillaglass unter Systemeinstellungen > Datenschutz & Sicherheit > Bildschirmaufnahme und versuche es erneut.",
    inputTrackingDegraded:
      "Input Monitoring ist abgelehnt. Aufnahme läuft weiter, aber Auto-Zoom-Trigger und Klick-Highlights sind deaktiviert.",
  },
  sections: {
    leftRail: "Sitzungssteuerung",
    center: "Vorschau-Bereich",
    timeline: "Zeitleiste",
    inspector: "Inspektor",
  },
  modes: {
    capture: "Aufnahme",
    edit: "Bearbeiten",
    deliver: "Liefern",
  },
  workspace: {
    editStageTitle: "Editor-Bereich",
    deliverSummaryTitle: "Lieferzusammenfassung",
    deliverSummarySubtitle: "Finale Ausgabeeinstellungen und Projektmetadaten",
    exportTitle: "Export",
    exportSubtitle: "Typsicheres Lieferformular mit validierungsbereiter Struktur",
  },
  actions: {
    refresh: "Aktualisieren",
    requestScreen: "Bildschirm anfragen",
    requestMic: "Mikrofon anfragen",
    requestInput: "Eingabe anfragen",
    openSettings: "Einstellungen öffnen",
    startPreview: "Vorschau starten",
    stopPreview: "Vorschau stoppen",
    startRecording: "Aufzeichnung starten",
    stopRecording: "Aufzeichnung stoppen",
    exportNow: "Exportieren",
    openProject: "Projekt öffnen",
    saveProject: "Projekt speichern",
    saveProjectAs: "Speichern unter",
    openRecent: "Zuletzt geöffnetes öffnen",
    playPause: "Wiedergabe/Pause",
    setTrimIn: "In setzen",
    setTrimOut: "Out setzen",
    timelineToolSelect: "Auswahl",
    timelineToolTrim: "Trim",
    timelineToolBlade: "Klinge",
    timelineZoomIn: "Zoom +",
    timelineZoomOut: "Zoom -",
    timelineZoomReset: "Zoom zurücksetzen",
    toggleLeftPane: "Linkes Panel umschalten",
    toggleRightPane: "Inspektor umschalten",
    toggleTimeline: "Zeitleiste umschalten",
    resetLayout: "Layout zurücksetzen",
  },
  shortcuts: {
    title: "Kurzbefehle",
    playPause: "Leertaste",
    record: "R",
    blade: "B",
    trimIn: "I",
    trimOut: "O",
    save: "Cmd/Ctrl+S",
    saveAs: "Cmd/Ctrl+Shift+S",
    export: "Cmd/Ctrl+E",
  },
  labels: {
    language: "Sprache",
    density: "Dichte",
    densityComfortable: "Komfortabel",
    densityCompact: "Kompakt",
    localeEnglish: "English (US)",
    localeGerman: "Deutsch (DE)",
    permissionReady: "Bildschirmberechtigung bereit",
    permissionRequired: "Bildschirmberechtigung erforderlich",
    screen: "Bildschirm",
    microphone: "Mikrofon",
    captureSource: "Aufnahmequelle",
    display: "Bildschirm",
    window: "Fenster",
    noWindows: "Keine Fenster verfügbar",
    includeMic: "Mikrofon einschließen",
    trackInput: "Cursor + Klicks erfassen",
    singleKeyShortcuts: "Single-Key-Kurzbefehle aktivieren",
    inputMonitoring: "Input Monitoring",
    status: "Status",
    duration: "Dauer",
    droppedFrames: "Verworfene Frames",
    audioLevel: "Audiopegel",
    health: "Gesundheit",
    recordingURL: "Aufzeichnungs-URL",
    projectPath: "Projektpfad",
    eventsURL: "Ereignis-URL",
    notSaved: "(nicht gespeichert)",
    idle: "inaktiv",
    previewing: "vorschau",
    recording: "aufzeichnung",
    trimInSeconds: "Trim In (s)",
    trimOutSeconds: "Trim Out (s)",
    playhead: "Abspielkopf",
    timelineTools: "Zeitleisten-Werkzeuge",
    timelineSnap: "Snap",
    timelineRipple: "Ripple",
    timelineZoom: "Zeitleisten-Zoom",
    timelineLaneLock: "Spur sperren",
    timelineLaneMute: "Spur stummschalten",
    timelineLaneSolo: "Spur solo",
    playbackRate: "Abspielgeschwindigkeit",
    preset: "Preset",
    fileName: "Dateiname",
    activeProject: "Aktives Projekt",
    projectUtilitySubtitle: "Projekt-Hilfsbereich und Schnellaktionen",
    projectName: "Projektname",
    captureSourceMetadata: "Aufnahmequelle",
    captureResolution: "Aufnahmeresolution",
    captureScale: "Aufnahmeskalierung",
    recentProjects: "Zuletzt geöffnete Projekte",
    lastOpened: "Zuletzt geöffnet",
    loadingRecentProjects: "Letzte Projekte werden geladen...",
    noRecentProjects: "Noch keine letzten Projekte",
    mediaBin: "Medien-Bin",
    mediaReady: "Bereit",
    mediaMissing: "Quelle fehlt",
    sourceMonitor: "Quellen-Monitor",
    audioMixer: "Audio-Mixer",
    masterChannel: "Master",
    mute: "Stumm",
    unmute: "Stummschaltung aufheben",
    autoZoomSection: "Auto-Zoom",
    autoZoomEnabled: "Auto-Zoom aktiviert",
    autoZoomIntensity: (value: number) => `Auto-Zoom-Intensität (${value}%)`,
    minimumKeyframeInterval: "Min. Keyframe-Intervall (s)",
    backgroundFraming: "Hintergrundrahmen",
    backgroundPadding: "Hintergrundabstand",
    cornerRoundness: "Eckenrundung",
    shadowStrength: "Schattenstärke",
    motionBlur: "Bewegungsunschärfe",
    simulatorAutoCrop: "Simulator-Auto-Crop",
    segmentOverrides: "Segment-spezifische Overrides",
    phaseTwoLabel: "Phase 2",
    phaseThreeLabel: "Phase 3",
    sourceWindowList: "Erkannte Fenster",
    sourceWindowApp: "App",
    sourceWindowTitle: "Titel",
    sourceWindowSize: "Größe",
    timelineLaneVideo: "Video",
    timelineLaneAudio: "Audio",
    timelineLaneEvents: "Ereignisse",
    timelineMarkerMove: "Bewegung",
    timelineMarkerClick: "Klick",
    timelineMarkerMixed: "Gemischt",
    timelineClipAria: (laneLabel: string, startSeconds: number, endSeconds: number) =>
      `${laneLabel}-Clip ${startSeconds.toFixed(2)} bis ${endSeconds.toFixed(2)} Sekunden`,
    timelineMarkerAria: (markerKindLabel: string, timestampSeconds: number) =>
      `Ereignismarker ${markerKindLabel} bei ${timestampSeconds.toFixed(2)} Sekunden`,
    resizeTimeline: "Zeitleiste in der Größe ändern",
    resizeLeftPane: "Linkes Panel in der Größe ändern",
    resizeRightPane: "Rechtes Panel in der Größe ändern",
  },
  values: {
    granted: "erteilt",
    notGranted: "nicht erteilt",
    unknown: "unbekannt",
    good: "gut",
    warning: "warnung",
    critical: "kritisch",
    untitled: "(ohne Titel)",
    on: "ein",
    off: "aus",
  },
  inspectorTabs: {
    capture: "Aufnahme",
    effects: "Effekte",
    export: "Export",
    project: "Projekt",
    advanced: "Erweitert",
  },
  inspector: {
    views: {
      timelineClipVideo: {
        title: "Video-Clip-Inspektor",
        subtitle: "Auswahlabhängige Zeit- und Trim-Steuerung",
      },
      timelineClipAudio: {
        title: "Audio-Clip-Inspektor",
        subtitle: "Auswahlabhängige Zeit- und Trim-Steuerung",
      },
      timelineMarker: {
        title: "Ereignis-Marker-Inspektor",
        subtitle: "Details zur Eingabeereignis-Auswahl und Schnellaktionen",
      },
      captureWindow: {
        title: "Fenster-Inspektor",
        subtitle: "Details zur gewählten Quelle und Aufnahme-Steuerung",
      },
      exportPreset: {
        title: "Preset-Inspektor",
        subtitle: "Details zum gewählten Export-Preset und Lieferkontext",
      },
      captureDefault: {
        title: "Aufnahme-Inspektor",
        subtitle: "Mikrofon-, Eingabe-Tracking- und Automationssteuerung",
      },
      editDefault: {
        title: "Editier-Inspektor",
        subtitle: "Auswahlabhängige Editiersteuerung",
      },
      deliverDefault: {
        title: "Liefer-Inspektor",
        subtitle: "Exportkontext und aktives Preset",
      },
    },
    cards: {
      selectedClip: "Ausgewählter Clip",
      selectedEventMarker: "Ausgewählter Ereignis-Marker",
      selectedWindow: "Ausgewähltes Fenster",
      selectedPreset: "Ausgewähltes Preset",
      activePreset: "Aktives Preset",
      trimWindow: "Trim-Fenster",
    },
    fields: {
      lane: "Spur",
      start: "Start",
      end: "Ende",
      duration: "Dauer",
      type: "Typ",
      time: "Zeit",
      density: "Dichte",
      app: "App",
      title: "Titel",
      windowId: "Fenster-ID",
      fileType: "Dateityp",
    },
    actions: {
      setTrimInToClipStart: "Trim In auf Clip-Anfang setzen",
      setTrimOutToClipEnd: "Trim Out auf Clip-Ende setzen",
      jumpPlayheadToMarker: "Abspielkopf zum Marker springen",
    },
  },
  helper: {
    degradedModeTitle: "Eingeschränkter Automationsmodus",
    degradedModeBody:
      "Aktiviere Input Monitoring in den Systemeinstellungen, um Klick-Highlights und eingabebasierten Auto-Zoom wiederherzustellen.",
    emptyPreviewTitle: "Keine aktive Vorschau",
    emptyPreviewBody:
      "Starte die Vorschau, zeichne auf und scrubbe in der Zeitleiste für präzise Trims und Export.",
    activePreviewTitle: "Live-Vorschau aktiv",
    activePreviewBody: "Aufnahme- und Aufzeichnungsstatus kommen live aus der nativen Engine.",
    phaseScaffoldTitle: "Zukünftige Steuerelemente vorbereitet",
    phaseScaffoldBody:
      "Hintergrundrahmung, Bewegungsunschärfe, segmentbezogene Overrides und Simulator-Auto-Crop sind hier für die phasenweise native Anbindung vorbereitet.",
    healthReasonEngineError: "Engine hat einen Aufnahmefehler gemeldet",
    healthReasonHighDroppedFrameRate: "Hohe Frame-Verwurfrate",
    healthReasonElevatedDroppedFrameRate: "Erhöhte Frame-Verwurfrate",
    healthReasonLowMicrophoneLevel: "Niedriger Mikrofonpegel",
    singleKeyShortcuts:
      "Single-Key-Kurzbefehle (R/I/O/Leertaste) greifen nur, wenn der Fokus nicht auf interaktiven Steuerelementen liegt.",
    recordToEnableAction:
      "Nimm mindestens einen Take auf, bevor du Projektschnappschüsse speicherst oder Exporte auslieferst.",
  },
};
