export const enUS = {
  app: {
    title: "Guerillaglass",
    subtitle: "Desktop Editor Shell",
    shellState: "Spec-aligned capture and editing workflow",
  },
  notices: {
    refreshFailed: "Failed to refresh app state.",
    actionFailed: "Action failed.",
    rpcTimedOut: "RPC request timed out. Try again or close open file dialogs first.",
    directoryPickerTimedOut:
      "Directory picker timed out before completing. Reopen the action when ready.",
    permissionsRefreshed: "Permissions refreshed.",
    captureStarted: "Capture preview started.",
    previewStateMismatch:
      "Preview command sent, but engine state did not confirm live preview yet. Check source permissions and retry.",
    captureStopped: "Capture stopped.",
    recordingStarted: "Recording started.",
    recordingFinished: "Recording finished.",
    exportMissingRecording: "No recording available to export.",
    exportMissingPreset: "No export preset selected.",
    exportComplete: (outputURL: string) => `Export complete: ${outputURL}`,
    projectOpened: "Project opened.",
    projectSaved: (path: string) => `Project saved to ${path}`,
    selectWindowFirst: "Select a window before starting capture.",
    screenPermissionRequired:
      "Screen Recording permission is required. Enable Guerillaglass in System Settings > Privacy & Security > Screen Recording, then retry.",
    inputTrackingDegraded:
      "Input Monitoring is denied. Recording continues, but auto-zoom triggers and click highlights are disabled.",
  },
  sections: {
    leftRail: "Session Controls",
    center: "Preview Stage",
    timeline: "Timeline",
    inspector: "Inspector",
  },
  modes: {
    capture: "Capture",
    edit: "Edit",
    deliver: "Deliver",
  },
  workspace: {
    editStageTitle: "Editor Stage",
    deliverSummaryTitle: "Delivery Summary",
    deliverSummarySubtitle: "Final output settings and project metadata",
    exportTitle: "Export",
    exportSubtitle: "Type-safe delivery form with validation-ready shape",
  },
  actions: {
    refresh: "Refresh",
    requestScreen: "Request Screen",
    requestMic: "Request Mic",
    requestInput: "Request Input",
    openSettings: "Open Settings",
    startPreview: "Start Preview",
    stopPreview: "Stop Preview",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    exportNow: "Export",
    openProject: "Open Project",
    saveProject: "Save Project",
    saveProjectAs: "Save As",
    openRecent: "Open Recent",
    playPause: "Play/Pause",
    setTrimIn: "Set In",
    setTrimOut: "Set Out",
    timelineToolSelect: "Select",
    timelineToolTrim: "Trim",
    timelineToolBlade: "Blade",
    timelineZoomIn: "Zoom In",
    timelineZoomOut: "Zoom Out",
    timelineZoomReset: "Reset Zoom",
    toggleLeftPane: "Toggle Left Pane",
    toggleRightPane: "Toggle Inspector",
    toggleTimeline: "Toggle Timeline",
    resetLayout: "Reset Layout",
  },
  shortcuts: {
    title: "Shortcuts",
    playPause: "Space",
    record: "R",
    blade: "B",
    trimIn: "I",
    trimOut: "O",
    save: "Cmd/Ctrl+S",
    saveAs: "Cmd/Ctrl+Shift+S",
    export: "Cmd/Ctrl+E",
  },
  labels: {
    language: "Language",
    density: "Density",
    densityComfortable: "Comfortable",
    densityCompact: "Compact",
    localeEnglish: "English (US)",
    localeGerman: "Deutsch (DE)",
    permissionReady: "Screen Permission Ready",
    permissionRequired: "Screen Permission Required",
    screen: "Screen",
    microphone: "Mic",
    captureSource: "Capture Source",
    display: "Display",
    window: "Window",
    noWindows: "No windows available",
    includeMic: "Include microphone",
    trackInput: "Track cursor + clicks",
    singleKeyShortcuts: "Enable single-key shortcuts",
    inputMonitoring: "Input Monitoring",
    status: "Status",
    duration: "Duration",
    droppedFrames: "Dropped Frames",
    audioLevel: "Audio Level",
    health: "Health",
    recordingURL: "Recording URL",
    projectPath: "Project Path",
    eventsURL: "Events URL",
    notSaved: "(not saved)",
    idle: "idle",
    previewing: "previewing",
    recording: "recording",
    trimInSeconds: "Trim In (s)",
    trimOutSeconds: "Trim Out (s)",
    playhead: "Playhead",
    timelineTools: "Timeline Tools",
    timelineSnap: "Snap",
    timelineRipple: "Ripple",
    timelineZoom: "Timeline Zoom",
    timelineLaneLock: "Lock lane",
    timelineLaneMute: "Mute lane",
    timelineLaneSolo: "Solo lane",
    playbackRate: "Playback Speed",
    preset: "Preset",
    fileName: "File Name",
    activeProject: "Active Project",
    projectUtilitySubtitle: "Project utility and quick actions",
    projectName: "Project Name",
    captureSourceMetadata: "Capture Source",
    captureResolution: "Capture Resolution",
    captureScale: "Capture Scale",
    recentProjects: "Recent Projects",
    lastOpened: "Last Opened",
    loadingRecentProjects: "Loading recent projects...",
    noRecentProjects: "No recent projects yet",
    mediaBin: "Media Bin",
    mediaReady: "Ready",
    mediaMissing: "Missing source",
    sourceMonitor: "Source Monitor",
    audioMixer: "Audio Mixer",
    masterChannel: "Master",
    mute: "Mute",
    unmute: "Unmute",
    autoZoomSection: "Auto Zoom",
    autoZoomEnabled: "Auto-zoom enabled",
    autoZoomIntensity: (value: number) => `Auto-zoom intensity (${value}%)`,
    minimumKeyframeInterval: "Min keyframe interval (s)",
    backgroundFraming: "Background framing",
    backgroundPadding: "Background padding",
    cornerRoundness: "Corner roundness",
    shadowStrength: "Shadow strength",
    motionBlur: "Motion blur",
    simulatorAutoCrop: "Simulator auto-crop",
    segmentOverrides: "Per-segment overrides",
    phaseTwoLabel: "Phase 2",
    phaseThreeLabel: "Phase 3",
    sourceWindowList: "Detected Windows",
    sourceWindowApp: "App",
    sourceWindowTitle: "Title",
    sourceWindowSize: "Size",
    timelineLaneVideo: "Video",
    timelineLaneAudio: "Audio",
    timelineLaneEvents: "Events",
    timelineMarkerMove: "move",
    timelineMarkerClick: "click",
    timelineMarkerMixed: "mixed",
    timelineClipAria: (laneLabel: string, startSeconds: number, endSeconds: number) =>
      `${laneLabel} clip ${startSeconds.toFixed(2)} to ${endSeconds.toFixed(2)} seconds`,
    timelineMarkerAria: (markerKindLabel: string, timestampSeconds: number) =>
      `Event marker ${markerKindLabel} at ${timestampSeconds.toFixed(2)} seconds`,
    resizeTimeline: "Resize timeline",
    resizeLeftPane: "Resize left panel",
    resizeRightPane: "Resize right panel",
  },
  values: {
    granted: "granted",
    notGranted: "not granted",
    unknown: "unknown",
    good: "good",
    warning: "warning",
    critical: "critical",
    untitled: "(untitled)",
    on: "on",
    off: "off",
  },
  inspectorTabs: {
    capture: "Capture",
    effects: "Effects",
    export: "Export",
    project: "Project",
    advanced: "Advanced",
  },
  inspector: {
    views: {
      timelineClipVideo: {
        title: "Video Clip Inspector",
        subtitle: "Selection-aware timing and trim controls",
      },
      timelineClipAudio: {
        title: "Audio Clip Inspector",
        subtitle: "Selection-aware timing and trim controls",
      },
      timelineMarker: {
        title: "Event Marker Inspector",
        subtitle: "Input event selection details and quick actions",
      },
      captureWindow: {
        title: "Window Inspector",
        subtitle: "Selected source details and capture controls",
      },
      exportPreset: {
        title: "Preset Inspector",
        subtitle: "Selected export preset details and delivery context",
      },
      captureDefault: {
        title: "Capture Inspector",
        subtitle: "Mic, input tracking, and automation controls",
      },
      editDefault: {
        title: "Edit Inspector",
        subtitle: "Selection-aware editing controls",
      },
      deliverDefault: {
        title: "Deliver Inspector",
        subtitle: "Export context and active preset",
      },
    },
    cards: {
      selectedClip: "Selected Clip",
      selectedEventMarker: "Selected Event Marker",
      selectedWindow: "Selected Window",
      selectedPreset: "Selected Preset",
      activePreset: "Active Preset",
      trimWindow: "Trim Window",
    },
    fields: {
      lane: "Lane",
      start: "Start",
      end: "End",
      duration: "Duration",
      type: "Type",
      time: "Time",
      density: "Density",
      app: "App",
      title: "Title",
      windowId: "Window ID",
      fileType: "File Type",
    },
    actions: {
      setTrimInToClipStart: "Set Trim In To Clip Start",
      setTrimOutToClipEnd: "Set Trim Out To Clip End",
      jumpPlayheadToMarker: "Jump Playhead To Marker",
    },
  },
  helper: {
    degradedModeTitle: "Degraded Automation Mode",
    degradedModeBody:
      "Enable Input Monitoring in System Settings to restore click highlights and input-triggered auto-zoom.",
    emptyPreviewTitle: "No active preview",
    emptyPreviewBody:
      "Start preview, then record and scrub in timeline for precise trims and export.",
    activePreviewTitle: "Live preview active",
    activePreviewBody: "Capture and recording state is live from the native engine.",
    phaseScaffoldTitle: "Future Controls Scaffolded",
    phaseScaffoldBody:
      "Background framing, motion blur, per-segment overrides, and Simulator auto-crop are surfaced here for phased native wiring.",
    healthReasonEngineError: "Engine reported a capture error",
    healthReasonHighDroppedFrameRate: "High dropped-frame rate",
    healthReasonElevatedDroppedFrameRate: "Elevated dropped-frame rate",
    healthReasonLowMicrophoneLevel: "Low microphone level",
    singleKeyShortcuts:
      "Single-key shortcuts (R/I/O/Space) only fire when focus is outside interactive controls.",
    recordToEnableAction:
      "Record at least one take before saving project snapshots or exporting deliverables.",
  },
} as const;

type WidenLiterals<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends boolean
      ? boolean
      : T extends (...args: infer TArgs) => infer TResult
        ? (...args: TArgs) => TResult
        : T extends readonly (infer U)[]
          ? readonly WidenLiterals<U>[]
          : T extends object
            ? { [K in keyof T]: WidenLiterals<T[K]> }
            : T;

export type StudioMessages = WidenLiterals<typeof enUS>;
